#!/usr/bin/perl


sub install
{
    my $config_file;

    if (-e ($config_file = "/etc/snmp/snmpd.conf") ||
	-e ($config_file = "/etc/snmpd.conf"))
    {
	my $tag = "dlmod iscsiTargetMib /usr/lib/snmp/dlmod/iscsiTargetMib.so\n";
	my $body = `cat $config_file`;
	
	$body =~ s/dlmod.*iscsiTargetMib.so\n//g;
	$body .= $tag;

	$body =~ s/view.*.*.enterprises.1055\n//g;
	$body =~ s/^(view\s+systemview\s+included)/view    systemview    included   enterprises.1055\n$1/m;
	$body =~ s/rocommunity\s+public\s+127.0.0.1/rocommunity public/g;
	
	open(FILE,">$config_file") || die "Could not recreate $config_file";
	print FILE $body;
	close FILE;
    }
}

sub uninstall
{
    my $config_file;

    if (-e ($config_file = "/etc/snmp/snmpd.conf") ||
        -e ($config_file = "/etc/snmpd.conf"))
    {
        my $body = `cat $config_file`;

	$body =~ s/view.*.*.enterprises.1055\n//g;

	$body =~ s/dlmod.*iscsiTargetMib.so\n//g;
	
	open(FILE,">$config_file") || die "Could not recreate $config_file";
        print FILE $body;
        close FILE;
    }
}








$action = shift @ARGV;

if ($action eq "install")
{
    install(@ARGV);
}
elsif ($action eq "uninstall")
{
    uninstall(@ARGV);
}
else
{
    die "Error";
}









